#+ summary: Testing DBpedia endpoint
#+ endpoint: http://dbpedia.org/sparql
#+ tags:
#+   - dbpedia
#+ method: GET
#+ pagination: 50
#+ defaults:
#+   - type: http://dbpedia.org/ontology/Band

select distinct ?s where {?s a ?_type_iri} LIMIT 20
