#+ summary: Number of NL housing types according to residence status, location and year		
#+ endpoint: http://virtuoso.clariah-sdh.eculture.labs.vu.nl/sparql		
#+ tags:		
#+   - SPARQL		
#+ enumerate:		
#+   - residenceStatus:
#+	- http://lod.cedar-project.nl/vocab/cedar-residenceStatus#AltijdAanwezig
#+	- http://lod.cedar-project.nl/vocab/cedar-residenceStatus#TijdelijkAanwezig
#+   - Kom:
#+	- http://lod.cedar-project.nl/vocab/cedar-Kom#BinnenKom
#+	- http://lod.cedar-project.nl/vocab/cedar-Kom#BuitenKom
#+   - year:
#+	- 1879
#+	- 1889
#+	- 1899
#+   - houseType:
#+	- http://lod.cedar-project.nl/vocab/cedar#house-BewoondeSchepen
#+	- http://lod.cedar-project.nl/vocab/cedar#house-BewoondeWagens
#+   - location:
#+	- http://www.gemeentegeschiedenis.nl/amco/10002
#+	- http://www.gemeentegeschiedenis.nl/amco/10004
#+	- http://www.gemeentegeschiedenis.nl/amco/10005
#+	- http://www.gemeentegeschiedenis.nl/amco/10008
#+	- http://www.gemeentegeschiedenis.nl/amco/10017
#+	- http://www.gemeentegeschiedenis.nl/amco/10021
#+	- http://www.gemeentegeschiedenis.nl/amco/10022
#+	- http://www.gemeentegeschiedenis.nl/amco/10023
#+	- http://www.gemeentegeschiedenis.nl/amco/10027
#+	- http://www.gemeentegeschiedenis.nl/amco/10030
#+	- http://www.gemeentegeschiedenis.nl/amco/10033
#+	- http://www.gemeentegeschiedenis.nl/amco/10036
#+	- http://www.gemeentegeschiedenis.nl/amco/10037
#+	- http://www.gemeentegeschiedenis.nl/amco/10038
#+	- http://www.gemeentegeschiedenis.nl/amco/10040
#+	- http://www.gemeentegeschiedenis.nl/amco/10042
#+	- http://www.gemeentegeschiedenis.nl/amco/10043
#+	- http://www.gemeentegeschiedenis.nl/amco/10046
#+	- http://www.gemeentegeschiedenis.nl/amco/10050
#+	- http://www.gemeentegeschiedenis.nl/amco/10052
#+	- http://www.gemeentegeschiedenis.nl/amco/10054
#+	- http://www.gemeentegeschiedenis.nl/amco/10057
#+	- http://www.gemeentegeschiedenis.nl/amco/10058
#+	- http://www.gemeentegeschiedenis.nl/amco/10059
#+	- http://www.gemeentegeschiedenis.nl/amco/10060
#+	- http://www.gemeentegeschiedenis.nl/amco/10065
#+	- http://www.gemeentegeschiedenis.nl/amco/10067
#+	- http://www.gemeentegeschiedenis.nl/amco/10068
#+	- http://www.gemeentegeschiedenis.nl/amco/10072
#+	- http://www.gemeentegeschiedenis.nl/amco/10073
#+	- http://www.gemeentegeschiedenis.nl/amco/10077
#+	- http://www.gemeentegeschiedenis.nl/amco/10078
#+	- http://www.gemeentegeschiedenis.nl/amco/10079
#+	- http://www.gemeentegeschiedenis.nl/amco/10080
#+	- http://www.gemeentegeschiedenis.nl/amco/10081
#+	- http://www.gemeentegeschiedenis.nl/amco/10082
#+	- http://www.gemeentegeschiedenis.nl/amco/10085
#+	- http://www.gemeentegeschiedenis.nl/amco/10086
#+	- http://www.gemeentegeschiedenis.nl/amco/10087
#+	- http://www.gemeentegeschiedenis.nl/amco/10089
#+	- http://www.gemeentegeschiedenis.nl/amco/10092
#+	- http://www.gemeentegeschiedenis.nl/amco/10093
#+	- http://www.gemeentegeschiedenis.nl/amco/10095
#+	- http://www.gemeentegeschiedenis.nl/amco/10101
#+	- http://www.gemeentegeschiedenis.nl/amco/10105
#+	- http://www.gemeentegeschiedenis.nl/amco/10111
#+	- http://www.gemeentegeschiedenis.nl/amco/10115
#+	- http://www.gemeentegeschiedenis.nl/amco/10116
#+	- http://www.gemeentegeschiedenis.nl/amco/10120
#+	- http://www.gemeentegeschiedenis.nl/amco/10121
#+	- http://www.gemeentegeschiedenis.nl/amco/10125
#+	- http://www.gemeentegeschiedenis.nl/amco/10126
#+	- http://www.gemeentegeschiedenis.nl/amco/10127
#+	- http://www.gemeentegeschiedenis.nl/amco/10128
#+	- http://www.gemeentegeschiedenis.nl/amco/10129
#+	- http://www.gemeentegeschiedenis.nl/amco/10130
#+	- http://www.gemeentegeschiedenis.nl/amco/10134
#+	- http://www.gemeentegeschiedenis.nl/amco/10136
#+	- http://www.gemeentegeschiedenis.nl/amco/10140
#+	- http://www.gemeentegeschiedenis.nl/amco/10142
#+	- http://www.gemeentegeschiedenis.nl/amco/10147
#+	- http://www.gemeentegeschiedenis.nl/amco/10151
#+	- http://www.gemeentegeschiedenis.nl/amco/10152
#+	- http://www.gemeentegeschiedenis.nl/amco/10154
#+	- http://www.gemeentegeschiedenis.nl/amco/10156
#+	- http://www.gemeentegeschiedenis.nl/amco/10157
#+	- http://www.gemeentegeschiedenis.nl/amco/10159
#+	- http://www.gemeentegeschiedenis.nl/amco/10160
#+	- http://www.gemeentegeschiedenis.nl/amco/10164
#+	- http://www.gemeentegeschiedenis.nl/amco/10165
#+	- http://www.gemeentegeschiedenis.nl/amco/10167
#+	- http://www.gemeentegeschiedenis.nl/amco/10168
#+	- http://www.gemeentegeschiedenis.nl/amco/10169
#+	- http://www.gemeentegeschiedenis.nl/amco/10172
#+	- http://www.gemeentegeschiedenis.nl/amco/10173
#+	- http://www.gemeentegeschiedenis.nl/amco/10174
#+	- http://www.gemeentegeschiedenis.nl/amco/10175
#+	- http://www.gemeentegeschiedenis.nl/amco/10177
#+	- http://www.gemeentegeschiedenis.nl/amco/10179
#+	- http://www.gemeentegeschiedenis.nl/amco/10180
#+	- http://www.gemeentegeschiedenis.nl/amco/10182
#+	- http://www.gemeentegeschiedenis.nl/amco/10183
#+	- http://www.gemeentegeschiedenis.nl/amco/10185
#+	- http://www.gemeentegeschiedenis.nl/amco/10186
#+	- http://www.gemeentegeschiedenis.nl/amco/10187
#+	- http://www.gemeentegeschiedenis.nl/amco/10188
#+	- http://www.gemeentegeschiedenis.nl/amco/10191
#+	- http://www.gemeentegeschiedenis.nl/amco/10192
#+	- http://www.gemeentegeschiedenis.nl/amco/10193
#+	- http://www.gemeentegeschiedenis.nl/amco/10197
#+	- http://www.gemeentegeschiedenis.nl/amco/10198
#+	- http://www.gemeentegeschiedenis.nl/amco/10199
#+	- http://www.gemeentegeschiedenis.nl/amco/10203
#+	- http://www.gemeentegeschiedenis.nl/amco/10204
#+	- http://www.gemeentegeschiedenis.nl/amco/10205
#+	- http://www.gemeentegeschiedenis.nl/amco/10206
#+	- http://www.gemeentegeschiedenis.nl/amco/10208
#+	- http://www.gemeentegeschiedenis.nl/amco/10215
#+	- http://www.gemeentegeschiedenis.nl/amco/10217
#+	- http://www.gemeentegeschiedenis.nl/amco/10222
#+	- http://www.gemeentegeschiedenis.nl/amco/10224
#+	- http://www.gemeentegeschiedenis.nl/amco/10227
#+	- http://www.gemeentegeschiedenis.nl/amco/10233
#+	- http://www.gemeentegeschiedenis.nl/amco/10240
#+	- http://www.gemeentegeschiedenis.nl/amco/10242
#+	- http://www.gemeentegeschiedenis.nl/amco/10244
#+	- http://www.gemeentegeschiedenis.nl/amco/10245
#+	- http://www.gemeentegeschiedenis.nl/amco/10246
#+	- http://www.gemeentegeschiedenis.nl/amco/10248
#+	- http://www.gemeentegeschiedenis.nl/amco/10250
#+	- http://www.gemeentegeschiedenis.nl/amco/10253
#+	- http://www.gemeentegeschiedenis.nl/amco/10254
#+	- http://www.gemeentegeschiedenis.nl/amco/10258
#+	- http://www.gemeentegeschiedenis.nl/amco/10259
#+	- http://www.gemeentegeschiedenis.nl/amco/10261
#+	- http://www.gemeentegeschiedenis.nl/amco/10262
#+	- http://www.gemeentegeschiedenis.nl/amco/10267
#+	- http://www.gemeentegeschiedenis.nl/amco/10270
#+	- http://www.gemeentegeschiedenis.nl/amco/10271
#+	- http://www.gemeentegeschiedenis.nl/amco/10272
#+	- http://www.gemeentegeschiedenis.nl/amco/10276
#+	- http://www.gemeentegeschiedenis.nl/amco/10279
#+	- http://www.gemeentegeschiedenis.nl/amco/10281
#+	- http://www.gemeentegeschiedenis.nl/amco/10282
#+	- http://www.gemeentegeschiedenis.nl/amco/10285
#+	- http://www.gemeentegeschiedenis.nl/amco/10287
#+	- http://www.gemeentegeschiedenis.nl/amco/10289
#+	- http://www.gemeentegeschiedenis.nl/amco/10290
#+	- http://www.gemeentegeschiedenis.nl/amco/10291
#+	- http://www.gemeentegeschiedenis.nl/amco/10293
#+	- http://www.gemeentegeschiedenis.nl/amco/10295
#+	- http://www.gemeentegeschiedenis.nl/amco/10298
#+	- http://www.gemeentegeschiedenis.nl/amco/10300
#+	- http://www.gemeentegeschiedenis.nl/amco/10302
#+	- http://www.gemeentegeschiedenis.nl/amco/10303
#+	- http://www.gemeentegeschiedenis.nl/amco/10304
#+	- http://www.gemeentegeschiedenis.nl/amco/10308
#+	- http://www.gemeentegeschiedenis.nl/amco/10309
#+	- http://www.gemeentegeschiedenis.nl/amco/10310
#+	- http://www.gemeentegeschiedenis.nl/amco/10312
#+	- http://www.gemeentegeschiedenis.nl/amco/10316
#+	- http://www.gemeentegeschiedenis.nl/amco/10318
#+	- http://www.gemeentegeschiedenis.nl/amco/10322
#+	- http://www.gemeentegeschiedenis.nl/amco/10324
#+	- http://www.gemeentegeschiedenis.nl/amco/10326
#+	- http://www.gemeentegeschiedenis.nl/amco/10327
#+	- http://www.gemeentegeschiedenis.nl/amco/10329
#+	- http://www.gemeentegeschiedenis.nl/amco/10330
#+	- http://www.gemeentegeschiedenis.nl/amco/10331
#+	- http://www.gemeentegeschiedenis.nl/amco/10334
#+	- http://www.gemeentegeschiedenis.nl/amco/10338
#+	- http://www.gemeentegeschiedenis.nl/amco/10340
#+	- http://www.gemeentegeschiedenis.nl/amco/10341
#+	- http://www.gemeentegeschiedenis.nl/amco/10342
#+	- http://www.gemeentegeschiedenis.nl/amco/10344
#+	- http://www.gemeentegeschiedenis.nl/amco/10345
#+	- http://www.gemeentegeschiedenis.nl/amco/10346
#+	- http://www.gemeentegeschiedenis.nl/amco/10349
#+	- http://www.gemeentegeschiedenis.nl/amco/10356
#+	- http://www.gemeentegeschiedenis.nl/amco/10357
#+	- http://www.gemeentegeschiedenis.nl/amco/10361
#+	- http://www.gemeentegeschiedenis.nl/amco/10362
#+	- http://www.gemeentegeschiedenis.nl/amco/10364
#+	- http://www.gemeentegeschiedenis.nl/amco/10365
#+	- http://www.gemeentegeschiedenis.nl/amco/10366
#+	- http://www.gemeentegeschiedenis.nl/amco/10369
#+	- http://www.gemeentegeschiedenis.nl/amco/10372
#+	- http://www.gemeentegeschiedenis.nl/amco/10373
#+	- http://www.gemeentegeschiedenis.nl/amco/10374
#+	- http://www.gemeentegeschiedenis.nl/amco/10375
#+	- http://www.gemeentegeschiedenis.nl/amco/10376
#+	- http://www.gemeentegeschiedenis.nl/amco/10377
#+	- http://www.gemeentegeschiedenis.nl/amco/10379
#+	- http://www.gemeentegeschiedenis.nl/amco/10381
#+	- http://www.gemeentegeschiedenis.nl/amco/10383
#+	- http://www.gemeentegeschiedenis.nl/amco/10385
#+	- http://www.gemeentegeschiedenis.nl/amco/10387
#+	- http://www.gemeentegeschiedenis.nl/amco/10393
#+	- http://www.gemeentegeschiedenis.nl/amco/10394
#+	- http://www.gemeentegeschiedenis.nl/amco/10395
#+	- http://www.gemeentegeschiedenis.nl/amco/10396
#+	- http://www.gemeentegeschiedenis.nl/amco/10397
#+	- http://www.gemeentegeschiedenis.nl/amco/10401
#+	- http://www.gemeentegeschiedenis.nl/amco/10402
#+	- http://www.gemeentegeschiedenis.nl/amco/10404
#+	- http://www.gemeentegeschiedenis.nl/amco/10405
#+	- http://www.gemeentegeschiedenis.nl/amco/10407
#+	- http://www.gemeentegeschiedenis.nl/amco/10408
#+	- http://www.gemeentegeschiedenis.nl/amco/10409
#+	- http://www.gemeentegeschiedenis.nl/amco/10410
#+	- http://www.gemeentegeschiedenis.nl/amco/10416
#+	- http://www.gemeentegeschiedenis.nl/amco/10417
#+	- http://www.gemeentegeschiedenis.nl/amco/10419
#+	- http://www.gemeentegeschiedenis.nl/amco/10422
#+	- http://www.gemeentegeschiedenis.nl/amco/10425
#+	- http://www.gemeentegeschiedenis.nl/amco/10426
#+	- http://www.gemeentegeschiedenis.nl/amco/10427
#+	- http://www.gemeentegeschiedenis.nl/amco/10440
#+	- http://www.gemeentegeschiedenis.nl/amco/10441
#+	- http://www.gemeentegeschiedenis.nl/amco/10443
#+	- http://www.gemeentegeschiedenis.nl/amco/10446
#+	- http://www.gemeentegeschiedenis.nl/amco/10448
#+	- http://www.gemeentegeschiedenis.nl/amco/10453
#+	- http://www.gemeentegeschiedenis.nl/amco/10454
#+	- http://www.gemeentegeschiedenis.nl/amco/10460
#+	- http://www.gemeentegeschiedenis.nl/amco/10461
#+	- http://www.gemeentegeschiedenis.nl/amco/10467
#+	- http://www.gemeentegeschiedenis.nl/amco/10468
#+	- http://www.gemeentegeschiedenis.nl/amco/10469
#+	- http://www.gemeentegeschiedenis.nl/amco/10470
#+	- http://www.gemeentegeschiedenis.nl/amco/10471
#+	- http://www.gemeentegeschiedenis.nl/amco/10477
#+	- http://www.gemeentegeschiedenis.nl/amco/10478
#+	- http://www.gemeentegeschiedenis.nl/amco/10479
#+	- http://www.gemeentegeschiedenis.nl/amco/10481
#+	- http://www.gemeentegeschiedenis.nl/amco/10483
#+	- http://www.gemeentegeschiedenis.nl/amco/10484
#+	- http://www.gemeentegeschiedenis.nl/amco/10485
#+	- http://www.gemeentegeschiedenis.nl/amco/10486
#+	- http://www.gemeentegeschiedenis.nl/amco/10487
#+	- http://www.gemeentegeschiedenis.nl/amco/10489
#+	- http://www.gemeentegeschiedenis.nl/amco/10490
#+	- http://www.gemeentegeschiedenis.nl/amco/10491
#+	- http://www.gemeentegeschiedenis.nl/amco/10495
#+	- http://www.gemeentegeschiedenis.nl/amco/10497
#+	- http://www.gemeentegeschiedenis.nl/amco/10498
#+	- http://www.gemeentegeschiedenis.nl/amco/10501
#+	- http://www.gemeentegeschiedenis.nl/amco/10502
#+	- http://www.gemeentegeschiedenis.nl/amco/10506
#+	- http://www.gemeentegeschiedenis.nl/amco/10508
#+	- http://www.gemeentegeschiedenis.nl/amco/10511
#+	- http://www.gemeentegeschiedenis.nl/amco/10517
#+	- http://www.gemeentegeschiedenis.nl/amco/10518
#+	- http://www.gemeentegeschiedenis.nl/amco/10520
#+	- http://www.gemeentegeschiedenis.nl/amco/10521
#+	- http://www.gemeentegeschiedenis.nl/amco/10522
#+	- http://www.gemeentegeschiedenis.nl/amco/10527
#+	- http://www.gemeentegeschiedenis.nl/amco/10532
#+	- http://www.gemeentegeschiedenis.nl/amco/10537
#+	- http://www.gemeentegeschiedenis.nl/amco/10539
#+	- http://www.gemeentegeschiedenis.nl/amco/10540
#+	- http://www.gemeentegeschiedenis.nl/amco/10542
#+	- http://www.gemeentegeschiedenis.nl/amco/10543
#+	- http://www.gemeentegeschiedenis.nl/amco/10544
#+	- http://www.gemeentegeschiedenis.nl/amco/10546
#+	- http://www.gemeentegeschiedenis.nl/amco/10550
#+	- http://www.gemeentegeschiedenis.nl/amco/10557
#+	- http://www.gemeentegeschiedenis.nl/amco/10558
#+	- http://www.gemeentegeschiedenis.nl/amco/10559
#+	- http://www.gemeentegeschiedenis.nl/amco/10603
#+	- http://www.gemeentegeschiedenis.nl/amco/10604
#+	- http://www.gemeentegeschiedenis.nl/amco/10605
#+	- http://www.gemeentegeschiedenis.nl/amco/10606
#+	- http://www.gemeentegeschiedenis.nl/amco/10608
#+	- http://www.gemeentegeschiedenis.nl/amco/10610
#+	- http://www.gemeentegeschiedenis.nl/amco/10616
#+	- http://www.gemeentegeschiedenis.nl/amco/10617
#+	- http://www.gemeentegeschiedenis.nl/amco/10618
#+	- http://www.gemeentegeschiedenis.nl/amco/10619
#+	- http://www.gemeentegeschiedenis.nl/amco/10620
#+	- http://www.gemeentegeschiedenis.nl/amco/10622
#+	- http://www.gemeentegeschiedenis.nl/amco/10624
#+	- http://www.gemeentegeschiedenis.nl/amco/10627
#+	- http://www.gemeentegeschiedenis.nl/amco/10628
#+	- http://www.gemeentegeschiedenis.nl/amco/10629
#+	- http://www.gemeentegeschiedenis.nl/amco/10630
#+	- http://www.gemeentegeschiedenis.nl/amco/10639
#+	- http://www.gemeentegeschiedenis.nl/amco/10643
#+	- http://www.gemeentegeschiedenis.nl/amco/10646
#+	- http://www.gemeentegeschiedenis.nl/amco/10647
#+	- http://www.gemeentegeschiedenis.nl/amco/10648
#+	- http://www.gemeentegeschiedenis.nl/amco/10649
#+	- http://www.gemeentegeschiedenis.nl/amco/10650
#+	- http://www.gemeentegeschiedenis.nl/amco/10656
#+	- http://www.gemeentegeschiedenis.nl/amco/10671
#+	- http://www.gemeentegeschiedenis.nl/amco/10672
#+	- http://www.gemeentegeschiedenis.nl/amco/10673
#+	- http://www.gemeentegeschiedenis.nl/amco/10674
#+	- http://www.gemeentegeschiedenis.nl/amco/10675
#+	- http://www.gemeentegeschiedenis.nl/amco/10676
#+	- http://www.gemeentegeschiedenis.nl/amco/10677
#+	- http://www.gemeentegeschiedenis.nl/amco/10680
#+	- http://www.gemeentegeschiedenis.nl/amco/10681
#+	- http://www.gemeentegeschiedenis.nl/amco/10682
#+	- http://www.gemeentegeschiedenis.nl/amco/10683
#+	- http://www.gemeentegeschiedenis.nl/amco/10684
#+	- http://www.gemeentegeschiedenis.nl/amco/10685
#+	- http://www.gemeentegeschiedenis.nl/amco/10689
#+	- http://www.gemeentegeschiedenis.nl/amco/10694
#+	- http://www.gemeentegeschiedenis.nl/amco/10695
#+	- http://www.gemeentegeschiedenis.nl/amco/10696
#+	- http://www.gemeentegeschiedenis.nl/amco/10699
#+	- http://www.gemeentegeschiedenis.nl/amco/10701
#+	- http://www.gemeentegeschiedenis.nl/amco/10702
#+	- http://www.gemeentegeschiedenis.nl/amco/10704
#+	- http://www.gemeentegeschiedenis.nl/amco/10706
#+	- http://www.gemeentegeschiedenis.nl/amco/10707
#+	- http://www.gemeentegeschiedenis.nl/amco/10708
#+	- http://www.gemeentegeschiedenis.nl/amco/10711
#+	- http://www.gemeentegeschiedenis.nl/amco/10712
#+	- http://www.gemeentegeschiedenis.nl/amco/10714
#+	- http://www.gemeentegeschiedenis.nl/amco/10715
#+	- http://www.gemeentegeschiedenis.nl/amco/10716
#+	- http://www.gemeentegeschiedenis.nl/amco/10722
#+	- http://www.gemeentegeschiedenis.nl/amco/10728
#+	- http://www.gemeentegeschiedenis.nl/amco/10729
#+	- http://www.gemeentegeschiedenis.nl/amco/10731
#+	- http://www.gemeentegeschiedenis.nl/amco/10732
#+	- http://www.gemeentegeschiedenis.nl/amco/10734
#+	- http://www.gemeentegeschiedenis.nl/amco/10735
#+	- http://www.gemeentegeschiedenis.nl/amco/10742
#+	- http://www.gemeentegeschiedenis.nl/amco/10744
#+	- http://www.gemeentegeschiedenis.nl/amco/10746
#+	- http://www.gemeentegeschiedenis.nl/amco/10747
#+	- http://www.gemeentegeschiedenis.nl/amco/10748
#+	- http://www.gemeentegeschiedenis.nl/amco/10750
#+	- http://www.gemeentegeschiedenis.nl/amco/10753
#+	- http://www.gemeentegeschiedenis.nl/amco/10757
#+	- http://www.gemeentegeschiedenis.nl/amco/10760
#+	- http://www.gemeentegeschiedenis.nl/amco/10765
#+	- http://www.gemeentegeschiedenis.nl/amco/10768
#+	- http://www.gemeentegeschiedenis.nl/amco/10773
#+	- http://www.gemeentegeschiedenis.nl/amco/10774
#+	- http://www.gemeentegeschiedenis.nl/amco/10776
#+	- http://www.gemeentegeschiedenis.nl/amco/10781
#+	- http://www.gemeentegeschiedenis.nl/amco/10783
#+	- http://www.gemeentegeschiedenis.nl/amco/10786
#+	- http://www.gemeentegeschiedenis.nl/amco/10787
#+	- http://www.gemeentegeschiedenis.nl/amco/10788
#+	- http://www.gemeentegeschiedenis.nl/amco/10789
#+	- http://www.gemeentegeschiedenis.nl/amco/10792
#+	- http://www.gemeentegeschiedenis.nl/amco/10795
#+	- http://www.gemeentegeschiedenis.nl/amco/10798
#+	- http://www.gemeentegeschiedenis.nl/amco/10799
#+	- http://www.gemeentegeschiedenis.nl/amco/10805
#+	- http://www.gemeentegeschiedenis.nl/amco/10806
#+	- http://www.gemeentegeschiedenis.nl/amco/10807
#+	- http://www.gemeentegeschiedenis.nl/amco/10809
#+	- http://www.gemeentegeschiedenis.nl/amco/10811
#+	- http://www.gemeentegeschiedenis.nl/amco/10814
#+	- http://www.gemeentegeschiedenis.nl/amco/10815
#+	- http://www.gemeentegeschiedenis.nl/amco/10816
#+	- http://www.gemeentegeschiedenis.nl/amco/10819
#+	- http://www.gemeentegeschiedenis.nl/amco/10820
#+	- http://www.gemeentegeschiedenis.nl/amco/10821
#+	- http://www.gemeentegeschiedenis.nl/amco/10823
#+	- http://www.gemeentegeschiedenis.nl/amco/10825
#+	- http://www.gemeentegeschiedenis.nl/amco/10826
#+	- http://www.gemeentegeschiedenis.nl/amco/10827
#+	- http://www.gemeentegeschiedenis.nl/amco/10830
#+	- http://www.gemeentegeschiedenis.nl/amco/10832
#+	- http://www.gemeentegeschiedenis.nl/amco/10834
#+	- http://www.gemeentegeschiedenis.nl/amco/10836
#+	- http://www.gemeentegeschiedenis.nl/amco/10838
#+	- http://www.gemeentegeschiedenis.nl/amco/10839
#+	- http://www.gemeentegeschiedenis.nl/amco/10843
#+	- http://www.gemeentegeschiedenis.nl/amco/10847
#+	- http://www.gemeentegeschiedenis.nl/amco/10848
#+	- http://www.gemeentegeschiedenis.nl/amco/10851
#+	- http://www.gemeentegeschiedenis.nl/amco/10853
#+	- http://www.gemeentegeschiedenis.nl/amco/10854
#+	- http://www.gemeentegeschiedenis.nl/amco/10858
#+	- http://www.gemeentegeschiedenis.nl/amco/10859
#+	- http://www.gemeentegeschiedenis.nl/amco/10862
#+	- http://www.gemeentegeschiedenis.nl/amco/10864
#+	- http://www.gemeentegeschiedenis.nl/amco/10865
#+	- http://www.gemeentegeschiedenis.nl/amco/10867
#+	- http://www.gemeentegeschiedenis.nl/amco/10870
#+	- http://www.gemeentegeschiedenis.nl/amco/10871
#+	- http://www.gemeentegeschiedenis.nl/amco/10875
#+	- http://www.gemeentegeschiedenis.nl/amco/10877
#+	- http://www.gemeentegeschiedenis.nl/amco/10880
#+	- http://www.gemeentegeschiedenis.nl/amco/10881
#+	- http://www.gemeentegeschiedenis.nl/amco/10884
#+	- http://www.gemeentegeschiedenis.nl/amco/10885
#+	- http://www.gemeentegeschiedenis.nl/amco/10886
#+	- http://www.gemeentegeschiedenis.nl/amco/10887
#+	- http://www.gemeentegeschiedenis.nl/amco/10888
#+	- http://www.gemeentegeschiedenis.nl/amco/10890
#+	- http://www.gemeentegeschiedenis.nl/amco/10891
#+	- http://www.gemeentegeschiedenis.nl/amco/10894
#+	- http://www.gemeentegeschiedenis.nl/amco/10895
#+	- http://www.gemeentegeschiedenis.nl/amco/10898
#+	- http://www.gemeentegeschiedenis.nl/amco/10899
#+	- http://www.gemeentegeschiedenis.nl/amco/10903
#+	- http://www.gemeentegeschiedenis.nl/amco/10904
#+	- http://www.gemeentegeschiedenis.nl/amco/10905
#+	- http://www.gemeentegeschiedenis.nl/amco/10907
#+	- http://www.gemeentegeschiedenis.nl/amco/10909
#+	- http://www.gemeentegeschiedenis.nl/amco/10911
#+	- http://www.gemeentegeschiedenis.nl/amco/10912
#+	- http://www.gemeentegeschiedenis.nl/amco/10914
#+	- http://www.gemeentegeschiedenis.nl/amco/10915
#+	- http://www.gemeentegeschiedenis.nl/amco/10916
#+	- http://www.gemeentegeschiedenis.nl/amco/10917
#+	- http://www.gemeentegeschiedenis.nl/amco/10918
#+	- http://www.gemeentegeschiedenis.nl/amco/10919
#+	- http://www.gemeentegeschiedenis.nl/amco/10923
#+	- http://www.gemeentegeschiedenis.nl/amco/10925
#+	- http://www.gemeentegeschiedenis.nl/amco/10928
#+	- http://www.gemeentegeschiedenis.nl/amco/10930
#+	- http://www.gemeentegeschiedenis.nl/amco/10931
#+	- http://www.gemeentegeschiedenis.nl/amco/10932
#+	- http://www.gemeentegeschiedenis.nl/amco/10933
#+	- http://www.gemeentegeschiedenis.nl/amco/10934
#+	- http://www.gemeentegeschiedenis.nl/amco/10938
#+	- http://www.gemeentegeschiedenis.nl/amco/10940
#+	- http://www.gemeentegeschiedenis.nl/amco/10942
#+	- http://www.gemeentegeschiedenis.nl/amco/10943
#+	- http://www.gemeentegeschiedenis.nl/amco/10944
#+	- http://www.gemeentegeschiedenis.nl/amco/10945
#+	- http://www.gemeentegeschiedenis.nl/amco/10948
#+	- http://www.gemeentegeschiedenis.nl/amco/10949
#+	- http://www.gemeentegeschiedenis.nl/amco/10950
#+	- http://www.gemeentegeschiedenis.nl/amco/10953
#+	- http://www.gemeentegeschiedenis.nl/amco/10954
#+	- http://www.gemeentegeschiedenis.nl/amco/10956
#+	- http://www.gemeentegeschiedenis.nl/amco/10957
#+	- http://www.gemeentegeschiedenis.nl/amco/10958
#+	- http://www.gemeentegeschiedenis.nl/amco/10961
#+	- http://www.gemeentegeschiedenis.nl/amco/10962
#+	- http://www.gemeentegeschiedenis.nl/amco/10964
#+	- http://www.gemeentegeschiedenis.nl/amco/10965
#+	- http://www.gemeentegeschiedenis.nl/amco/10968
#+	- http://www.gemeentegeschiedenis.nl/amco/10974
#+	- http://www.gemeentegeschiedenis.nl/amco/10976
#+	- http://www.gemeentegeschiedenis.nl/amco/10977
#+	- http://www.gemeentegeschiedenis.nl/amco/10979
#+	- http://www.gemeentegeschiedenis.nl/amco/10980
#+	- http://www.gemeentegeschiedenis.nl/amco/10982
#+	- http://www.gemeentegeschiedenis.nl/amco/10983
#+	- http://www.gemeentegeschiedenis.nl/amco/10984
#+	- http://www.gemeentegeschiedenis.nl/amco/10985
#+	- http://www.gemeentegeschiedenis.nl/amco/10988
#+	- http://www.gemeentegeschiedenis.nl/amco/10990
#+	- http://www.gemeentegeschiedenis.nl/amco/10996
#+	- http://www.gemeentegeschiedenis.nl/amco/10998
#+	- http://www.gemeentegeschiedenis.nl/amco/10999
#+	- http://www.gemeentegeschiedenis.nl/amco/11004
#+	- http://www.gemeentegeschiedenis.nl/amco/11007
#+	- http://www.gemeentegeschiedenis.nl/amco/11010
#+	- http://www.gemeentegeschiedenis.nl/amco/11011
#+	- http://www.gemeentegeschiedenis.nl/amco/11014
#+	- http://www.gemeentegeschiedenis.nl/amco/11016
#+	- http://www.gemeentegeschiedenis.nl/amco/11017
#+	- http://www.gemeentegeschiedenis.nl/amco/11023
#+	- http://www.gemeentegeschiedenis.nl/amco/11033
#+	- http://www.gemeentegeschiedenis.nl/amco/11035
#+	- http://www.gemeentegeschiedenis.nl/amco/11036
#+	- http://www.gemeentegeschiedenis.nl/amco/11037
#+	- http://www.gemeentegeschiedenis.nl/amco/11038
#+	- http://www.gemeentegeschiedenis.nl/amco/11039
#+	- http://www.gemeentegeschiedenis.nl/amco/11043
#+	- http://www.gemeentegeschiedenis.nl/amco/11044
#+	- http://www.gemeentegeschiedenis.nl/amco/11046
#+	- http://www.gemeentegeschiedenis.nl/amco/11047
#+	- http://www.gemeentegeschiedenis.nl/amco/11048
#+	- http://www.gemeentegeschiedenis.nl/amco/11049
#+	- http://www.gemeentegeschiedenis.nl/amco/11050
#+	- http://www.gemeentegeschiedenis.nl/amco/11053
#+	- http://www.gemeentegeschiedenis.nl/amco/11057
#+	- http://www.gemeentegeschiedenis.nl/amco/11058
#+	- http://www.gemeentegeschiedenis.nl/amco/11062
#+	- http://www.gemeentegeschiedenis.nl/amco/11064
#+	- http://www.gemeentegeschiedenis.nl/amco/11066
#+	- http://www.gemeentegeschiedenis.nl/amco/11067
#+	- http://www.gemeentegeschiedenis.nl/amco/11069
#+	- http://www.gemeentegeschiedenis.nl/amco/11071
#+	- http://www.gemeentegeschiedenis.nl/amco/11072
#+	- http://www.gemeentegeschiedenis.nl/amco/11074
#+	- http://www.gemeentegeschiedenis.nl/amco/11075
#+	- http://www.gemeentegeschiedenis.nl/amco/11077
#+	- http://www.gemeentegeschiedenis.nl/amco/11078
#+	- http://www.gemeentegeschiedenis.nl/amco/11079
#+	- http://www.gemeentegeschiedenis.nl/amco/11080
#+	- http://www.gemeentegeschiedenis.nl/amco/11081
#+	- http://www.gemeentegeschiedenis.nl/amco/11083
#+	- http://www.gemeentegeschiedenis.nl/amco/11085
#+	- http://www.gemeentegeschiedenis.nl/amco/11088
#+	- http://www.gemeentegeschiedenis.nl/amco/11091
#+	- http://www.gemeentegeschiedenis.nl/amco/11092
#+	- http://www.gemeentegeschiedenis.nl/amco/11093
#+	- http://www.gemeentegeschiedenis.nl/amco/11095
#+	- http://www.gemeentegeschiedenis.nl/amco/11097
#+	- http://www.gemeentegeschiedenis.nl/amco/11099
#+	- http://www.gemeentegeschiedenis.nl/amco/11100
#+	- http://www.gemeentegeschiedenis.nl/amco/11102
#+	- http://www.gemeentegeschiedenis.nl/amco/11106
#+	- http://www.gemeentegeschiedenis.nl/amco/11108
#+	- http://www.gemeentegeschiedenis.nl/amco/11109
#+	- http://www.gemeentegeschiedenis.nl/amco/11113
#+	- http://www.gemeentegeschiedenis.nl/amco/11118
#+	- http://www.gemeentegeschiedenis.nl/amco/11121
#+	- http://www.gemeentegeschiedenis.nl/amco/11122
#+	- http://www.gemeentegeschiedenis.nl/amco/11123
#+	- http://www.gemeentegeschiedenis.nl/amco/11125
#+	- http://www.gemeentegeschiedenis.nl/amco/11126
#+	- http://www.gemeentegeschiedenis.nl/amco/11129
#+	- http://www.gemeentegeschiedenis.nl/amco/11131
#+	- http://www.gemeentegeschiedenis.nl/amco/11135
#+	- http://www.gemeentegeschiedenis.nl/amco/11137
#+	- http://www.gemeentegeschiedenis.nl/amco/11141
#+	- http://www.gemeentegeschiedenis.nl/amco/11142
#+	- http://www.gemeentegeschiedenis.nl/amco/11144
#+	- http://www.gemeentegeschiedenis.nl/amco/11145
#+	- http://www.gemeentegeschiedenis.nl/amco/11147
#+	- http://www.gemeentegeschiedenis.nl/amco/11148
#+	- http://www.gemeentegeschiedenis.nl/amco/11150
#+	- http://www.gemeentegeschiedenis.nl/amco/11157
#+	- http://www.gemeentegeschiedenis.nl/amco/11160
#+	- http://www.gemeentegeschiedenis.nl/amco/11163
#+	- http://www.gemeentegeschiedenis.nl/amco/11166
#+	- http://www.gemeentegeschiedenis.nl/amco/11169
#+	- http://www.gemeentegeschiedenis.nl/amco/11170
#+	- http://www.gemeentegeschiedenis.nl/amco/11178
#+	- http://www.gemeentegeschiedenis.nl/amco/11180
#+	- http://www.gemeentegeschiedenis.nl/amco/11181
#+	- http://www.gemeentegeschiedenis.nl/amco/11182
#+	- http://www.gemeentegeschiedenis.nl/amco/11183
#+	- http://www.gemeentegeschiedenis.nl/amco/11184
#+	- http://www.gemeentegeschiedenis.nl/amco/11188
#+	- http://www.gemeentegeschiedenis.nl/amco/11190
#+	- http://www.gemeentegeschiedenis.nl/amco/11191
#+	- http://www.gemeentegeschiedenis.nl/amco/11193
#+	- http://www.gemeentegeschiedenis.nl/amco/11199
#+	- http://www.gemeentegeschiedenis.nl/amco/11200
#+	- http://www.gemeentegeschiedenis.nl/amco/11202
#+	- http://www.gemeentegeschiedenis.nl/amco/11204
#+	- http://www.gemeentegeschiedenis.nl/amco/11205
#+	- http://www.gemeentegeschiedenis.nl/amco/11206
#+	- http://www.gemeentegeschiedenis.nl/amco/11208
#+	- http://www.gemeentegeschiedenis.nl/amco/11209
#+	- http://www.gemeentegeschiedenis.nl/amco/11210
#+	- http://www.gemeentegeschiedenis.nl/amco/11212
#+	- http://www.gemeentegeschiedenis.nl/amco/11215
#+	- http://www.gemeentegeschiedenis.nl/amco/11218
#+	- http://www.gemeentegeschiedenis.nl/amco/11219
#+	- http://www.gemeentegeschiedenis.nl/amco/11225
#+	- http://www.gemeentegeschiedenis.nl/amco/11226
#+	- http://www.gemeentegeschiedenis.nl/amco/11228
#+	- http://www.gemeentegeschiedenis.nl/amco/11230
#+	- http://www.gemeentegeschiedenis.nl/amco/11233
#+	- http://www.gemeentegeschiedenis.nl/amco/11236
#+	- http://www.gemeentegeschiedenis.nl/amco/11237
#+	- http://www.gemeentegeschiedenis.nl/amco/11241
#+	- http://www.gemeentegeschiedenis.nl/amco/11242
#+	- http://www.gemeentegeschiedenis.nl/amco/11247
#+	- http://www.gemeentegeschiedenis.nl/amco/11248
#+	- http://www.gemeentegeschiedenis.nl/amco/11249
#+	- http://www.gemeentegeschiedenis.nl/amco/11257
#+	- http://www.gemeentegeschiedenis.nl/amco/11258
#+	- http://www.gemeentegeschiedenis.nl/amco/11260
#+	- http://www.gemeentegeschiedenis.nl/amco/11261
#+	- http://www.gemeentegeschiedenis.nl/amco/11264
#+	- http://www.gemeentegeschiedenis.nl/amco/11266
#+	- http://www.gemeentegeschiedenis.nl/amco/11277
#+	- http://www.gemeentegeschiedenis.nl/amco/11279
#+	- http://www.gemeentegeschiedenis.nl/amco/11280
#+	- http://www.gemeentegeschiedenis.nl/amco/11282
#+	- http://www.gemeentegeschiedenis.nl/amco/11284
#+	- http://www.gemeentegeschiedenis.nl/amco/11285
#+	- http://www.gemeentegeschiedenis.nl/amco/11286
#+	- http://www.gemeentegeschiedenis.nl/amco/11288
#+	- http://www.gemeentegeschiedenis.nl/amco/11291
#+	- http://www.gemeentegeschiedenis.nl/amco/11292
#+	- http://www.gemeentegeschiedenis.nl/amco/11294
#+	- http://www.gemeentegeschiedenis.nl/amco/11296
#+	- http://www.gemeentegeschiedenis.nl/amco/11301
#+	- http://www.gemeentegeschiedenis.nl/amco/11303
#+	- http://www.gemeentegeschiedenis.nl/amco/11305
#+	- http://www.gemeentegeschiedenis.nl/amco/11307
#+	- http://www.gemeentegeschiedenis.nl/amco/11308
#+	- http://www.gemeentegeschiedenis.nl/amco/11313
#+	- http://www.gemeentegeschiedenis.nl/amco/11317
#+	- http://www.gemeentegeschiedenis.nl/amco/11318
#+	- http://www.gemeentegeschiedenis.nl/amco/11320
#+	- http://www.gemeentegeschiedenis.nl/amco/11322
#+	- http://www.gemeentegeschiedenis.nl/amco/11324
#+	- http://www.gemeentegeschiedenis.nl/amco/11325
#+	- http://www.gemeentegeschiedenis.nl/amco/11327
#+	- http://www.gemeentegeschiedenis.nl/amco/11331
#+	- http://www.gemeentegeschiedenis.nl/amco/11332
#+	- http://www.gemeentegeschiedenis.nl/amco/11333
#+	- http://www.gemeentegeschiedenis.nl/amco/11339
#+	- http://www.gemeentegeschiedenis.nl/amco/11344
#+	- http://www.gemeentegeschiedenis.nl/amco/11346
#+	- http://www.gemeentegeschiedenis.nl/amco/11347
#+	- http://www.gemeentegeschiedenis.nl/amco/11348
#+	- http://www.gemeentegeschiedenis.nl/amco/11349
#+	- http://www.gemeentegeschiedenis.nl/amco/11351
#+	- http://www.gemeentegeschiedenis.nl/amco/11352
#+	- http://www.gemeentegeschiedenis.nl/amco/11355
#+	- http://www.gemeentegeschiedenis.nl/amco/11357
#+	- http://www.gemeentegeschiedenis.nl/amco/11359
#+	- http://www.gemeentegeschiedenis.nl/amco/11363
#+	- http://www.gemeentegeschiedenis.nl/amco/11369
#+	- http://www.gemeentegeschiedenis.nl/amco/11371
#+	- http://www.gemeentegeschiedenis.nl/amco/11372
#+	- http://www.gemeentegeschiedenis.nl/amco/11373
#+	- http://www.gemeentegeschiedenis.nl/amco/11376
#+	- http://www.gemeentegeschiedenis.nl/amco/11377
#+	- http://www.gemeentegeschiedenis.nl/amco/11379
#+	- http://www.gemeentegeschiedenis.nl/amco/11381
#+	- http://www.gemeentegeschiedenis.nl/amco/11387
#+	- http://www.gemeentegeschiedenis.nl/amco/11391
#+	- http://www.gemeentegeschiedenis.nl/amco/11392
#+	- http://www.gemeentegeschiedenis.nl/amco/11395
#+	- http://www.gemeentegeschiedenis.nl/amco/11396
#+	- http://www.gemeentegeschiedenis.nl/amco/11398
#+	- http://www.gemeentegeschiedenis.nl/amco/11404
#+	- http://www.gemeentegeschiedenis.nl/amco/11405
#+	- http://www.gemeentegeschiedenis.nl/amco/11411
#+	- http://www.gemeentegeschiedenis.nl/amco/11419
#+	- http://www.gemeentegeschiedenis.nl/amco/11421
#+	- http://www.gemeentegeschiedenis.nl/amco/11424
#+	- http://www.gemeentegeschiedenis.nl/amco/11427
#+	- http://www.gemeentegeschiedenis.nl/amco/11430
#+	- http://www.gemeentegeschiedenis.nl/amco/11431
#+	- http://www.gemeentegeschiedenis.nl/amco/11432
#+	- http://www.gemeentegeschiedenis.nl/amco/11433
#+	- http://www.gemeentegeschiedenis.nl/amco/11434
#+	- http://www.gemeentegeschiedenis.nl/amco/11436
#+	- http://www.gemeentegeschiedenis.nl/amco/11445


PREFIX cedar: <http://lod.cedar-project.nl:8888/cedar/resource/>
PREFIX maritalstatus: <http://lod.cedar-project.nl/vocab/cedar-maritalstatus#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmx-code: <http://purl.org/linked-data/sdmx/2009/code#>
PREFIX cedarterms: <http://lod.cedar-project.nl/vocab/cedar#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX gg: <http://www.gemeentegeschiedenis.nl/amco/>

SELECT (SUM(?pop) AS ?tot) FROM <urn:graph:cedar-mini:release> WHERE {
	?obs a qb:Observation.
	?obs sdmx-dimension:refArea ?_location_iri.
	?obs cedarterms:Kom ?_Kom_iri.
	?obs cedarterms:population ?pop.
	?slice a qb:Slice.
	?slice qb:observation ?obs.
	?slice sdmx-dimension:refPeriod ?_year_integer.
	?obs cedarterms:houseType ?_houseType_iri.
	?obs cedarterms:residenceStatus ?_residenceStatus_iri .
	FILTER (NOT EXISTS {?obs cedarterms:isTotal ?total })
}
