#+ endpoint: https://data.create.humanities.uva.nl/sparql
#+ tags:
#+  - dates

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?person rdf:type schema:Person ; # give me all things that are of type 'Person' as defined by the schema.org vocabulary and label that 'person'
  schema:birthDate ?birthDate ; # for these 'person's (things) provide me their birthdate;
       schema:deathDate ?deathDate ; # and their death date
       schema:name ?personName . # oh.. and and their name as well (just so we can keep track)
  FILTER (?birthDate < "1630-01-01"^^xsd:date) # now just keep the persons born before 1630
  FILTER (?deathDate > "1639-12-31"^^xsd:date) # AND those who died in 1640 or later
}
